# Base Image  
FROM node:8.12.0
ENV NODE_ENV=development
ENV PORT=3000
ENV YARN_VERSION=1.13.0
ENV BRANCH_ENV=master
RUN curl -fSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz" \
    && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ \
    && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn \
    && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg \
    && rm yarn-v$YARN_VERSION.tar.gz

WORKDIR /cbioportal-frontend
COPY package.json /cbioportal-frontend
COPY yarn.lock /cbioportal-frontend
COPY vendor-bundles.webpack.config.js /cbioportal-frontend
COPY scripts /cbioportal-frontend/scripts
RUN cd /cbioportal-frontend
RUN yarn install --frozen-lockfile
RUN yarn run buildDLL:dev

EXPOSE 3000
CMD ["yarn", "run", "start"]
