FROM circleci/node:8.12.0-browsers
MAINTAINER Pim van Nierop <pim@thehyve.nl>, Fedde Schaeffer <fedde@thehyve.nl>

LABEL Description="End-2-end test image for cBioPortal frontend"

COPY . /cbioportal

CMD yarn serveDist & \
    cd end-to-end-tests && \
    yarn install --frozen-lockfile && \
    ./node_modules/webdriver-manager/bin/webdriver-manager update --versions.chrome '2.42' && \
    ./node_modules/webdriver-manager/bin/webdriver-manager start --versions.chrome '2.42' & \
    curl $CBIOPORTAL_URL > /dev/null && \
    sleep 5s && \
    curl $CBIOPORTAL_URL > /dev/null && \
    sleep 5s && \
    curl $CBIOPORTAL_URL > /dev/null && \
    sleep 20s && \
    (curl --insecure https://localhost:3000 || curl http://localhost:3000) > /dev/null && \
    sleep 1s && \
    yarn run test-webdriver-manager